# Generated by Django 5.2.3 on 2025-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=100, verbose_name="Taille de l'entreprise"),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, verbose_name="Type d'entreprise"),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de Patente'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site Web'),
        ),
    ]
