# Generated by Django 5.2.3 on 2025-06-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='phone',
            new_name='phone_company',
        ),
    ]
