# Generated by Django 5.2.3 on 2025-06-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_companyprofile_patent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='permissions',
            field=models.JSONField(default=dict, verbose_name='Permissions spéciales'),
        ),
        migrations.AddField(
            model_name='authority',
            name='authority_level',
            field=models.CharField(blank=True, max_length=50, verbose_name="Niveau d'autorité"),
        ),
        migrations.AddField(
            model_name='authority',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('setting_type', models.CharField(choices=[('general', 'Général'), ('email', 'Email'), ('payment', 'Paiement'), ('security', 'Sécurité'), ('notification', 'Notification')], max_length=20, verbose_name='Type de paramètre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
                'ordering': ['setting_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du traitement')),
                ('description', models.TextField(verbose_name='Description')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('required_documents', models.JSONField(default=list, verbose_name='Documents requis')),
                ('processing_time_days', models.IntegerField(default=30, verbose_name='Délai de traitement (jours)')),
                ('laws_applicable', models.JSONField(default=list, verbose_name='Lois applicables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Type de traitement',
                'verbose_name_plural': 'Types de traitements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de base')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de traitement')),
                ('urgency_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3, verbose_name='Multiplicateur urgence')),
                ('company_size_multiplier', models.JSONField(default=dict, verbose_name='Multiplicateur taille entreprise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'à")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='accounts.treatmenttype')),
            ],
            options={
                'verbose_name': 'Frais de traitement',
                'verbose_name_plural': 'Frais de traitements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('approve', 'Approbation'), ('reject', 'Rejet')], max_length=20, verbose_name='Action')),
                ('target_model', models.CharField(max_length=100, verbose_name='Modèle cible')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='ID cible')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('additional_data', models.JSONField(default=dict, verbose_name='Données supplémentaires')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'ordering': ['-timestamp'],
            },
        ),
    ]
