# Generated by Django 5.2.3 on 2025-06-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_administrator_permissions_authority_authority_level_and_more'),
    ]

    operations = [
    ]
