# Generated by Django 5.2.3 on 2025-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250625_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='treatmenttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='authority_level',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.DeleteModel(
            name='ProcessingFee',
        ),
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
        migrations.DeleteModel(
            name='TreatmentType',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
