# Generated by Django 5.2.3 on 2025-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_systemconfiguration_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='ice_number',
            field=models.CharField(max_length=50, verbose_name='ICE'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='rc_number',
            field=models.CharField(max_length=50, verbose_name='RC'),
        ),
    ]
