# Generated by Django 5.2.3 on 2025-06-16 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(max_length=100, verbose_name='Type de traitement')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Date de soumission')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('under_review', 'En cours de révision'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('submitted_data', models.JSONField(default=dict, verbose_name='Données soumises')),
                ('supporting_documents', models.FileField(upload_to='certification_requests/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Documents justificatifs')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_requests', to='accounts.companyprofile')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_requests', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Demande de certification',
                'verbose_name_plural': 'Demandes de certification',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('treatment_type', models.CharField(max_length=100, verbose_name='Type de traitement')),
                ('pdf_file', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier PDF')),
                ('certification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='certifications.certificationrequest')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
        migrations.CreateModel(
            name='RejectionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(verbose_name='Commentaires')),
                ('date', models.DateField(auto_now_add=True)),
                ('certification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reports', to='certifications.certificationrequest')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Rapport de refus',
                'verbose_name_plural': 'Rapports de refus',
            },
        ),
    ]
