# Generated by Django 5.2.3 on 2025-06-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('waste_collected', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Déchets collectés (kg)')),
                ('waste_treated', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Déchets traités (kg)')),
                ('recycling_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de recyclage (%)')),
                ('energy_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consommation énergétique (kWh)')),
                ('carbon_footprint', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Empreinte carbone (kg CO2)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_infos', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Information journalière',
                'verbose_name_plural': 'Informations journalières',
                'unique_together': {('company', 'date')},
            },
        ),
    ]
