# Generated by Django 5.2.3 on 2025-06-22 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_certificate_expiry_date_certificate_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='certification_requests/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Documents justificatifs'),
        ),
    ]
