# Generated by Django 5.2.3 on 2025-06-23 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_alter_certificationrequest_supporting_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=100, unique=True, verbose_name='Type de traitement')),
                ('form_fields', models.JSONField(help_text='Structure JSON des champs', verbose_name='Champs du formulaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Formulaire dynamique',
                'verbose_name_plural': 'Formulaires dynamiques',
            },
        ),
        migrations.AddField(
            model_name='certificationrequest',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par'),
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('request', 'Demande'), ('certificate', 'Certificat'), ('rejection_report', 'Rapport de refus'), ('payment_receipt', 'Reçu de paiement'), ('supporting_document', 'Document justificatif')], max_length=30)),
                ('file_path', models.FileField(upload_to='archives/')),
                ('original_filename', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_documents', to='certifications.certificationrequest')),
            ],
            options={
                'verbose_name': 'Archive de document',
                'verbose_name_plural': 'Archives de documents',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(verbose_name='Données du formulaire')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_submission', to='certifications.certificationrequest')),
            ],
            options={
                'verbose_name': 'Soumission de formulaire',
                'verbose_name_plural': 'Soumissions de formulaires',
            },
        ),
        migrations.CreateModel(
            name='LawChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=100, verbose_name='Type de traitement')),
                ('law_reference', models.CharField(max_length=100, verbose_name='Référence de la loi')),
                ('law_title', models.CharField(max_length=255, verbose_name='Titre de la loi')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist des lois',
                'verbose_name_plural': 'Checklists des lois',
                'unique_together': {('treatment_type', 'law_reference')},
            },
        ),
    ]
