# Generated by Django 5.2.3 on 2025-06-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_dynamicform_certificationrequest_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier PDF'),
        ),
    ]
