# Generated by Django 5.2.3 on 2025-06-24 18:58

import certifications.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Document principal de la demande', null=True, upload_to=certifications.models.supporting_documents_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Document principal'),
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom du document')),
                ('document_type', models.CharField(choices=[('technical_report', 'Rapport technique'), ('environmental_study', 'Étude environnementale'), ('authorization', 'Autorisation'), ('certificate', 'Certificat'), ('invoice', 'Facture'), ('contract', 'Contrat'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=certifications.models.certification_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls'])], verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('certification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='certifications.certificationrequest')),
            ],
            options={
                'verbose_name': 'Document justificatif',
                'verbose_name_plural': 'Documents justificatifs',
            },
        ),
    ]
