# Generated by Django 5.2.3 on 2025-06-25 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0007_alter_certificationrequest_supporting_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('certificate_issued', 'Certificat émis'), ('audit_required', 'Audit requis'), ('expiry_warning', "Avertissement d'expiration"), ('report_ready', 'Rapport prêt'), ('compliance_issue', 'Problème de conformité'), ('regulatory_update', 'Mise à jour réglementaire'), ('system_alert', 'Alerte système')], max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('action_url', models.URLField(blank=True, null=True, verbose_name="URL d'action")),
                ('action_label', models.CharField(blank=True, max_length=50, null=True, verbose_name="Label d'action")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Ignoré')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authority_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification autorité',
                'verbose_name_plural': 'Notifications autorité',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='certificati_recipie_31c8cf_idx'), models.Index(fields=['notification_type'], name='certificati_notific_97ce34_idx'), models.Index(fields=['priority'], name='certificati_priorit_526f4c_idx'), models.Index(fields=['created_at'], name='certificati_created_8652d5_idx')],
            },
        ),
    ]
