# Generated by Django 5.2.3 on 2025-06-16 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference_number', models.CharField(max_length=50, verbose_name='Numéro de référence')),
                ('publication_date', models.DateField(verbose_name='Date de publication')),
                ('pdf_file', models.FileField(upload_to='laws/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loi',
                'verbose_name_plural': 'Lois',
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du traitement')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Exigences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de traitement',
                'verbose_name_plural': 'Types de traitement',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='regulations.law')),
            ],
            options={
                'verbose_name': 'Réglementation',
                'verbose_name_plural': 'Réglementations',
            },
        ),
    ]
