# Generated by Django 5.2.3 on 2025-06-22 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='law',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='law',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='law',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='law',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='law',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='treatmenttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatmenttype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='law',
            name='article',
            field=models.CharField(default='1', max_length=20, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='law',
            name='category',
            field=models.CharField(choices=[('waste_management', 'Gestion des déchets'), ('environmental', 'Environnement'), ('deee', 'DEEE'), ('certification', 'Certification'), ('compliance', 'Conformité')], default='deee', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='law',
            name='content',
            field=models.TextField(default='', verbose_name='Contenu complet'),
        ),
        migrations.AddField(
            model_name='law',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'entrée en vigueur"),
        ),
        migrations.AddField(
            model_name='law',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='law',
            name='number',
            field=models.CharField(default='28-00', max_length=50, verbose_name='Numéro de loi'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='applicable_sector',
            field=models.CharField(choices=[('all', 'Tous secteurs'), ('industrial', 'Industriel'), ('commercial', 'Commercial'), ('municipal', 'Municipal'), ('healthcare', 'Santé')], default='all', max_length=20, verbose_name='Secteur applicable'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='content',
            field=models.TextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'entrée en vigueur"),
        ),
        migrations.AddField(
            model_name='regulation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='Obligatoire'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='related_laws',
            field=models.ManyToManyField(blank=True, to='regulations.law', verbose_name='Lois liées'),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='applicable_laws',
            field=models.ManyToManyField(blank=True, to='regulations.law', verbose_name='Lois applicables'),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='certification_fee',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10, verbose_name='Frais de certification'),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='code',
            field=models.CharField(default='default', max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='treatmenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='treatmenttype',
            name='requirements',
            field=models.JSONField(default=dict, verbose_name='Exigences'),
        ),
    ]
