# Generated by Django 5.2.3 on 2025-06-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_feestructure_systemconfiguration_systemmetrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('new_request', 'Nouvelle demande de certification'), ('payment_received', 'Paiement reçu'), ('certificate_issued', 'Certificat émis'), ('user_registered', 'Nouvel utilisateur enregistré'), ('system_alert', 'Alerte système'), ('approval_needed', 'Approbation requise'), ('document_uploaded', 'Document téléchargé'), ('deadline_approaching', 'Échéance approche'), ('error_occurred', 'Erreur système'), ('maintenance', 'Maintenance')], max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet")),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('action_url', models.URLField(blank=True, null=True, verbose_name="URL d'action")),
                ('action_label', models.CharField(blank=True, max_length=50, null=True, verbose_name="Label d'action")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Ignoré')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification admin',
                'verbose_name_plural': 'Notifications admin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='regulations_recipie_40bb8d_idx'), models.Index(fields=['notification_type'], name='regulations_notific_f6903f_idx'), models.Index(fields=['priority'], name='regulations_priorit_e162d1_idx'), models.Index(fields=['created_at'], name='regulations_created_1344f5_idx')],
            },
        ),
    ]
